version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0

    steps:
      - checkout

      - run:
          name: Run tests
          command: mvn clean test
       
      - run:
          name: Remove incompatible TestNG report
          command: rm -f target/surefire-reports/testng-results.xml

      - store_test_results:
          path: target/surefire-reports/junitreports

      - store_artifacts:
          path: target

workflows:
  build_and_test:
    jobs:
      - build